const PREFIX = 'CART/';

export const ADD_TO_CART = PREFIX + 'ADD_TO_CART';

export const CHANGE_CART_QUANTITY = PREFIX + 'CHANGE_CART_QUANTITY';

export const CHECK_CART = PREFIX + 'CHECK_CART';

export const DEL_FROM_CART = PREFIX + 'DEL_FROM_CART';

export const TRANSFER_TO_USER_CART = PREFIX + 'TRANSFER_TO_USER_CART';

export const LOAD_CART = PREFIX + 'LOAD_CART';

export const SET_CART = PREFIX + 'SET_CART';
