const PREFIX = 'PRODUCT/';

export const FETCH_PRODUCT = PREFIX + 'FETCH_PRODUCT';

export const FETCH_COMMENTS = PREFIX + 'FETCH_COMMENTS';

export const SET_COMMENTS = PREFIX + 'SET_COMMENTS';

export const SET_COMMENT_COUNT = PREFIX + 'SET_COMMENT_COUNT';

export const SET_COMMENT_PAGE = PREFIX + 'SET_COMMENT_PAGE';

export const SET_COMMENT_AVG_STARS = PREFIX + 'SET_COMMENT_AVG_STARS';

export const SET_PRODUCT = PREFIX + 'SET_PRODUCT';

export const SET_SPECS = PREFIX + 'SET_SPECS';

export const COMMENTS_PER_PAGE = 10;
