const PREFIX = 'HOME/';

export const FETCH_CATEGORIES = PREFIX + 'FETCH_CATEGORIES';
export const SET_CATEGORIES = PREFIX + 'SET_CATEGORIES';

export const FETCH_CAROUSELS = PREFIX + 'FETCH_CAROUSELS';
export const SET_CAROUSELS = PREFIX + 'SET_CAROUSELS';
