const PREFIX = 'HOME/';

export const FETCH_CAROUSELS = PREFIX + 'FETCH_CAROUSELS';
export const SET_CAROUSELS = PREFIX + 'SET_CAROUSELS';

export const FETCH_NEW_PRODUCTS = PREFIX + 'FETCH_NEW_PRODUCTS';
export const SET_NEW_PRODUCTS = PREFIX + 'SET_NEW_PRODUCTS';

export const FETCH_RECOMMEND_PRODUCTS = PREFIX + 'FETCH_RECOMMEND_PRODUCTS';
export const SET_RECOMMEND_PRODUCTS = PREFIX + 'SET_RECOMMEND_PRODUCTS';

export const FETCH_BEST_SELL_PRODUCTS = PREFIX + 'FETCH_BEST_SELL_PRODUCTS';
export const SET_BEST_SELL_PRODUCTS = PREFIX + 'SET_BEST_SELL_PRODUCTS';

export const FETCH_TIME_PRODUCTS = PREFIX + 'FETCH_TIME_PRODUCTS';
export const SET_TIME_PRODUCTS = PREFIX + 'SET_TIME_PRODUCTS';
